"use client";

import { useState } from "react";
import { motion } from "motion/react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Brain, FileText, Headphones, Target, CheckCircle, Download, Loader2 } from "lucide-react";

export default function LandingPage() {
  const router = useRouter();
  const [isNavigating, setIsNavigating] = useState(false);

  const handleStartPracticing = () => {
    setIsNavigating(true);
  };

  const features = [
    {
      icon: <Brain className="w-6 h-6 text-gray-300" />,
      title: "AI Generated Questions",
      description: "Unlimited unique questions generated by advanced AI.",
    },
    {
      icon: <Target className="w-6 h-6 text-gray-300" />,
      title: "Exam-Level Difficulty",
      description: "Questions designed to match ICAP's rigorous standards.",
    },
    {
      icon: <FileText className="w-6 h-6 text-gray-300" />,
      title: "Past Paper Style",
      description: "Scenario-based conceptual questions.",
    },
    {
      icon: <CheckCircle className="w-6 h-6 text-gray-300" />,
      title: "Detailed Explanations",
      description: "Step-by-step reasoning for every option.",
    },
    {
      icon: <Headphones className="w-6 h-6 text-gray-300" />,
      title: "Audio Learning",
      description: "Listen to explanations with text-to-speech.",
    },
    {
      icon: <Download className="w-6 h-6 text-gray-300" />,
      title: "Download PDF",
      description: "Export questions and answers for offline practice.",
    },
  ];

  return (
    <div className="min-h-screen bg-black text-gray-100 font-sans selection:bg-gray-700 relative overflow-hidden">
      {/* Ambient Background Glow */}
      <div className="absolute top-[-20%] left-1/2 -translate-x-1/2 w-[800px] h-[600px] bg-gradient-to-b from-white/[0.06] to-transparent blur-3xl rounded-full pointer-events-none" />

      {/* Navigation */}
      <nav className="border-b border-white/10 bg-black/50 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Brain className="w-8 h-8 text-gray-200" />
            <span className="text-xl font-bold tracking-tight text-white">ICAP AI Prep</span>
          </div>
          <Link
            href="/generator"
            onClick={handleStartPracticing}
            className="text-sm font-medium text-black bg-gray-200 hover:bg-white px-4 py-2 rounded-full transition-colors flex items-center gap-2"
          >
            {isNavigating ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
            Start Practicing
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16 text-center relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="max-w-3xl mx-auto"
        >
          <h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight text-white mb-6 leading-tight">
            AI MCQ Generator for <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-gray-300 to-gray-500">
              ICAP Students
            </span>
          </h1>
          <p className="text-lg sm:text-xl text-gray-400 mb-10">
            Practice unlimited ICAP exam-level MCQs instantly using AI. Master your concepts with scenario-based questions and detailed explanations.
          </p>
          <Link
            href="/generator"
            onClick={handleStartPracticing}
            className="inline-flex items-center justify-center px-8 py-4 text-base font-semibold text-black bg-gray-100 hover:bg-white rounded-full shadow-lg hover:shadow-xl transition-all hover:-translate-y-1 gap-2"
          >
            {isNavigating ? <Loader2 className="w-5 h-5 animate-spin" /> : null}
            Start Practicing Now
          </Link>
        </motion.div>

        {/* Features Grid */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="mt-24 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8"
        >
          {features.map((feature, idx) => (
            <div
              key={idx}
              className="bg-[#111] border border-white/5 p-8 rounded-2xl hover:bg-[#151515] transition-colors text-left"
            >
              <div className="bg-white/10 w-12 h-12 rounded-xl flex items-center justify-center mb-6">
                {feature.icon}
              </div>
              <h3 className="text-xl font-semibold text-white mb-3">{feature.title}</h3>
              <p className="text-gray-400 leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </motion.div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/10 py-8 text-center text-gray-500 text-sm relative z-10">
        <p>Powered by Advanced AI. Not affiliated with ICAP.</p>
        <p className="mt-2 text-gray-400 font-medium">Built by Waleed Tanveer</p>
      </footer>
    </div>
  );
}
